var minigames = [
  {
    "ID": 10, 
    "index": 1, 
    "level": 1, 
    "max": 4, 
    "next": 11, 
    "symbol": "a", 
    "symbol2": "b", 
    "url": "whereis/fasta.html", 
    "url2": "whereis/turtle.html",
    "msg": [
    "<br />",
    "<p>Click on <span style=\"padding:10px;text-decoration: none;text-transform: uppercase;font-family: Arial, Helvetica, sans-serif;font-size: 14px;font-weight: normal;color: #FFFFFF;background-color:black;\">[ L e v e l # $level$ &mdash; g a m e # $game$ ]</span> to return to the mini-game </p>",
    "<br /><br />",
    "<p style=\"font-size: 150%\">The clue is in the URL &#9786;</p>",
    "<p style=\"font-size: 150%\">... and don't forget to add the extension <i>'.html'</i> &#9786;</p>"
    ],
    "history": [
      "2012/01/23: Help added",
      "2012/01/23: History created",
      "2012/01/23: Mini-game created",
      "2017/03/17: Refactoring with JS"
    ]
  }, 
  {
    "ID": 11, 
    "index": 2, 
    "level": 1, 
    "max": 4, 
    "next": 13, 
    "symbol": "c", 
    "symbol2": "d", 
    "url": "format/genbank.html", 
    "url2": "format/convolution.html"
  }, 
  {
    "ID": 13, 
    "index": 3, 
    "level": 1, 
    "max": 4, 
    "next": 15, 
    "symbol": "e", 
    "symbol2": "f", 
    "url": "text/crosswords.html", 
    "url2": "text/stadium.html"
  }, 
  {
    "ID": 15, 
    "index": 4, 
    "level": 1, 
    "max": 4, 
    "next": 9999, 
    "symbol": "g", 
    "symbol2": "h", 
    "url": "to/fasta_format.html", 
    "url2": "to/here.html"
  }, 
  {
    "ID": 21, 
    "index": 1, 
    "level": 2, 
    "max": 3, 
    "next": 22, 
    "symbol": "a", 
    "symbol2": "b", 
    "url": "storage/bank.html", 
    "url2": "storage/walking.html"
  }, 
  {
    "ID": 22, 
    "index": 2, 
    "level": 2, 
    "max": 3, 
    "next": 24, 
    "symbol": "c", 
    "symbol2": "d", 
    "url": "entrez/best.html", 
    "url2": "entrez/dongle.html"
  }, 
  {
    "ID": 24, 
    "index": 3, 
    "level": 2, 
    "max": 3, 
    "next": 9999, 
    "symbol": "e", 
    "symbol2": "f", 
    "url": "data/mining.html", 
    "url2": "data/awesome.html"
  }, 
  {
    "ID": 2, 
    "index": 1, 
    "level": 3, 
    "max": 5, 
    "next": 34, 
    "symbol": "a", 
    "symbol2": "b", 
    "url": "organism/name.html", 
    "url2": "organism/only_latin.html"
  }, 
  {
    "ID": 34, 
    "index": 2, 
    "level": 3, 
    "max": 5, 
    "next": 37, 
    "symbol": "c", 
    "symbol2": "d", 
    "url": "locus/code.html", 
    "url2": "locus/void.html"
  }, 
  {
    "ID": 37, 
    "index": 3, 
    "level": 3, 
    "max": 5, 
    "next": 38, 
    "symbol": "e", 
    "symbol2": "f", 
    "url": "pmid/ref.html", 
    "url2": "pmid/bibliography.html"
  }, 
  {
    "ID": 38, 
    "index": 4, 
    "level": 3, 
    "max": 5, 
    "next": 39, 
    "symbol": "g", 
    "symbol2": "h", 
    "url": "swiss/prot.html", 
    "url2": "swiss/neon.html"
  }, 
  {
    "ID": 39, 
    "index": 5, 
    "level": 3, 
    "max": 5, 
    "next": 9999, 
    "symbol": "i", 
    "symbol2": "j", 
    "url": "source/between.html", 
    "url2": "source/rpl2.html"
  }, 
  {
    "ID": 40, 
    "index": 1, 
    "level": 4, 
    "max": 5, 
    "next": 41, 
    "symbol": "a", 
    "symbol2": "b", 
    "url": "jump/keys.html", 
    "url2": "jump/intersect.html"
  }, 
  {
    "ID": 41, 
    "index": 4, 
    "level": 4, 
    "max": 4, 
    "next": 9999, 
    "symbol": "g", 
    "symbol2": "h", 
    "url": "mouse/settings.html", 
    "url2": "mouse/easy.html"
  }, 
  {
    "ID": 42, 
    "index": 3, 
    "level": 4, 
    "max": 5, 
    "next": 45, 
    "symbol": "e", 
    "symbol2": "f", 
    "url": "cheese/dessert.html", 
    "url2": "cheese/organic.html"
  }, 
  {
    "ID": 45, 
    "index": 5, 
    "level": 4, 
    "max": 5, 
    "next": 9999, 
    "symbol": "i", 
    "symbol2": "j", 
    "url": "entry/search.html", 
    "url2": "entry/acrab_tolc_pump.html"
  }, 
  {
    "ID": 51, 
    "index": 1, 
    "level": 5, 
    "max": 3, 
    "next": 52, 
    "symbol": "a", 
    "symbol2": "b", 
    "url": "date/speed.html", 
    "url2": "date/last_but_not_least.html"
  }, 
  {
    "ID": 52, 
    "index": 2, 
    "level": 5, 
    "max": 3, 
    "next": 57, 
    "symbol": "c", 
    "symbol2": "d", 
    "url": "filter/author.html", 
    "url2": "filter/paradise.html"
  }, 
  {
    "ID": 57, 
    "index": 3, 
    "level": 5, 
    "max": 3, 
    "next": 9999, 
    "symbol": "e", 
    "symbol2": "f", 
    "url": "lost/search.html", 
    "url2": "lost/thanks_a_lot.html"
  }, 
  {
    "ID": 61, 
    "index": 1, 
    "level": 6, 
    "max": 3, 
    "next": 62, 
    "symbol": "a", 
    "symbol2": "b", 
    "url": "rasmol/cpk_colors.html", 
    "url2": "rasmol/clocks.html"
  }, 
  {
    "ID": 62, 
    "index": 2, 
    "level": 6, 
    "max": 3, 
    "next": 64, 
    "symbol": "c", 
    "symbol2": "d", 
    "url": "animate/molecule.html", 
    "url2": "animate/nadph.html"
  }, 
  {
    "ID": 64, 
    "index": 3, 
    "level": 6, 
    "max": 3, 
    "next": 9999, 
    "symbol": "e", 
    "symbol2": "f", 
    "url": "atoms/pdb_to_fasta.html", 
    "url2": "atoms/cycle.html"
  }, 
  {
    "ID": 72, 
    "index": 1, 
    "level": 7, 
    "max": 4, 
    "next": 75, 
    "symbol": "a", 
    "symbol2": "b", 
    "url": "crazylab/walking.html", 
    "url2": "crazylab/362677.html"
  }, 
  {
    "ID": 75, 
    "index": 2, 
    "level": 7, 
    "max": 4, 
    "next": 77, 
    "symbol": "c", 
    "symbol2": "d", 
    "url": "computer/room.html", 
    "url2": "computer/guru.html"
  }, 
  {
    "ID": 77, 
    "index": 3, 
    "level": 7, 
    "max": 4, 
    "next": 78, 
    "symbol": "e", 
    "symbol2": "f", 
    "url": "install/continued.html", 
    "url2": "install/yesitis.html"
  }, 
  {
    "ID": 78, 
    "index": 4, 
    "level": 7, 
    "max": 4, 
    "next": 9999, 
    "symbol": "g", 
    "symbol2": "h", 
    "url": "workflow/tool.html", 
    "url2": "workflow/the_end.html"
  }, 
  {
    "ID": 83, 
    "index": 1, 
    "level": 8, 
    "max": 5, 
    "next": 84, 
    "symbol": "a", 
    "symbol2": "b", 
    "url": "length_of/sequence.html", 
    "url2": "length_of/arctocephalus_forsteri.html"
  }, 
  {
    "ID": 84, 
    "index": 2, 
    "level": 8, 
    "max": 5, 
    "next": 85, 
    "symbol": "c", 
    "symbol2": "d", 
    "url": "alpha/weight.html", 
    "url2": "alpha/upsilon.html"
  }, 
  {
    "ID": 85, 
    "index": 3, 
    "level": 8, 
    "max": 5, 
    "next": 87, 
    "symbol": "e", 
    "symbol2": "f", 
    "url": "aa/composition.html", 
    "url2": "aa/sixteen.html"
  }, 
  {
    "ID": 87, 
    "index": 4, 
    "level": 8, 
    "max": 5, 
    "next": 89, 
    "symbol": "g", 
    "symbol2": "h", 
    "url": "translate/seq.html", 
    "url2": "translate/computer.html"
  }, 
  {
    "ID": 89, 
    "index": 5, 
    "level": 8, 
    "max": 5, 
    "next": 9999, 
    "symbol": "i", 
    "symbol2": "j", 
    "url": "clean/sequence.html", 
    "url2": "clean/caterpillar.html"
  }, 
  {
    "ID": 91, 
    "index": 1, 
    "level": 9, 
    "max": 5, 
    "next": 92, 
    "symbol": "a", 
    "symbol2": "b", 
    "url": "twofortwo/align.html", 
    "url2": "twofortwo/oracle.html"
  }, 
  {
    "ID": 92, 
    "index": 2, 
    "level": 9, 
    "max": 5, 
    "next": 94, 
    "symbol": "c", 
    "symbol2": "d", 
    "url": "howmany/repeats.html", 
    "url2": "howmany/repair.html"
  }, 
  {
    "ID": 94, 
    "index": 3, 
    "level": 9, 
    "max": 5, 
    "next": 95, 
    "symbol": "e", 
    "symbol2": "f", 
    "url": "dottup/indel.html", 
    "url2": "dottup/aleajactaest.html"
  }, 
  {
    "ID": 95, 
    "index": 4, 
    "level": 9, 
    "max": 5, 
    "next": 98, 
    "symbol": "g", 
    "symbol2": "h", 
    "url": "plot/pattern.html", 
    "url2": "plot/dark.html"
  }, 
  {
    "ID": 98, 
    "index": 5, 
    "level": 9, 
    "max": 5, 
    "next": 9999, 
    "symbol": "i", 
    "symbol2": "j", 
    "url": "latin/lorem.html", 
    "url2": "latin/dark.html"
  }, 
  {
    "ID": 101, 
    "index": 1, 
    "level": 10, 
    "max": 5, 
    "next": 102, 
    "symbol": "a", 
    "symbol2": "b", 
    "url": "nucleic/matrix.html", 
    "url2": "nucleic/phosphorus.html"
  }, 
  {
    "ID": 102, 
    "index": 2, 
    "level": 10, 
    "max": 5, 
    "next": 104, 
    "symbol": "c", 
    "symbol2": "d", 
    "url": "score/value.html", 
    "url2": "score/alternate.html"
  }, 
  {
    "ID": 104, 
    "index": 3, 
    "level": 10, 
    "max": 5, 
    "next": 107, 
    "symbol": "e", 
    "symbol2": "f", 
    "url": "global/world.html", 
    "url2": "global/video.html"
  }, 
  {
    "ID": 107, 
    "index": 4, 
    "level": 10, 
    "max": 5, 
    "next": 108, 
    "symbol": "g", 
    "symbol2": "h", 
    "url": "pair/global.html", 
    "url2": "pair/sinister.html"
  }, 
  {
    "ID": 108, 
    "index": 5, 
    "level": 10, 
    "max": 5, 
    "next": 9999, 
    "symbol": "i", 
    "symbol2": "j", 
    "url": "needleman/wunsch.html", 
    "url2": "needleman/heroes.html"
  }, 
  {
    "ID": 110, 
    "index": 1, 
    "level": 11, 
    "max": 5, 
    "next": 111, 
    "symbol": "a", 
    "symbol2": "b", 
    "url": "sun/stars.html", 
    "url2": "sun/saucer.html"
  }, 
  {
    "ID": 111, 
    "index": 2, 
    "level": 11, 
    "max": 5, 
    "next": 113, 
    "symbol": "c", 
    "symbol2": "d", 
    "url": "acgt/processing.html", 
    "url2": "acgt/famous.html"
  }, 
  {
    "ID": 113, 
    "index": 3, 
    "level": 11, 
    "max": 5, 
    "next": 115, 
    "symbol": "e", 
    "symbol2": "f", 
    "url": "species/explore.html", 
    "url2": "species/phosphorus.html"
  }, 
  {
    "ID": 115, 
    "index": 4, 
    "level": 11, 
    "max": 5, 
    "next": 116, 
    "symbol": "g", 
    "symbol2": "h", 
    "url": "blast/splicing.html", 
    "url2": "blast/homo_sapiens_insulin.html"
  }, 
  {
    "ID": 116, 
    "index": 5, 
    "level": 11, 
    "max": 5, 
    "next": 9999, 
    "symbol": "i", 
    "symbol2": "j", 
    "url": "homolog/beast.html", 
    "url2": "homolog/rocket.html"
  }, 
  {
    "ID": 120, 
    "index": 1, 
    "level": 12, 
    "max": 2, 
    "next": 121, 
    "symbol": "a", 
    "symbol2": "b", 
    "url": "weight/molecule.html", 
    "url2": "weight/tubes.html"
  }, 
  {
    "ID": 121, 
    "index": 2, 
    "level": 12, 
    "max": 2, 
    "next": 9999, 
    "symbol": "c", 
    "symbol2": "d", 
    "url": "multi/align.html", 
    "url2": "multi/pass.html"
  }, 
  {
    "ID": 130, 
    "index": 1, 
    "level": 13, 
    "max": 5, 
    "next": 131, 
    "symbol": "a", 
    "symbol2": "b", 
    "url": "newick/format.html", 
    "url2": "newick/avenger.html"
  }, 
  {
    "ID": 131, 
    "index": 2, 
    "level": 13, 
    "max": 5, 
    "next": 133, 
    "symbol": "c", 
    "symbol2": "d", 
    "url": "kingdom/tree.html", 
    "url2": "kingdom/methanococcus_maripaludis.html"
  }, 
  {
    "ID": 133, 
    "index": 3, 
    "level": 13, 
    "max": 5, 
    "next": 135, 
    "symbol": "e", 
    "symbol2": "f", 
    "url": "ancestor/common.html", 
    "url2": "ancestor/uncle.html"
  }, 
  {
    "ID": 135, 
    "index": 4, 
    "level": 13, 
    "max": 5, 
    "next": 138, 
    "symbol": "g", 
    "symbol2": "h", 
    "url": "crocodile/dinosaur.html", 
    "url2": "crocodile/pet.html"
  }, 
  {
    "ID": 138, 
    "index": 5, 
    "level": 13, 
    "max": 5, 
    "next": 9999, 
    "symbol": "i", 
    "symbol2": "j", 
    "url": "simplify/cladogram.html", 
    "url2": "simplify/batman.html"
  }, 
  {
    "ID": 140, 
    "index": 1, 
    "level": 14, 
    "max": 5, 
    "next": 141, 
    "symbol": "a", 
    "symbol2": "b", 
    "url": "myo/globins.html", 
    "url2": "myo/tubes.html"
  }, 
  {
    "ID": 141, 
    "index": 2, 
    "level": 14, 
    "max": 5, 
    "next": 143, 
    "symbol": "c", 
    "symbol2": "d", 
    "url": "structure/whale.html", 
    "url2": "structure/ninja.html"
  }, 
  {
    "ID": 143, 
    "index": 3, 
    "level": 14, 
    "max": 5, 
    "next": 145, 
    "symbol": "e", 
    "symbol2": "f", 
    "url": "compare/structure.html", 
    "url2": "compare/conclusion.html"
  }, 
  {
    "ID": 145, 
    "index": 4, 
    "level": 14, 
    "max": 5, 
    "next": 148, 
    "symbol": "g", 
    "symbol2": "h", 
    "url": "broken/viewer.html", 
    "url2": "broken/cyanid.html"
  }, 
  {
    "ID": 148, 
    "index": 5, 
    "level": 14, 
    "max": 5, 
    "next": 9999, 
    "symbol": "i", 
    "symbol2": "j", 
    "url": "cross/viewpoint.html", 
    "url2": "cross/cyanid.html"
  }, 
  {
    "ID": 150, 
    "index": 1, 
    "level": 15, 
    "max": 5, 
    "next": 151, 
    "symbol": "a", 
    "symbol2": "b", 
    "url": "crime/scene.html", 
    "url2": "crime/coffin.html"
  }, 
  {
    "ID": 151, 
    "index": 2, 
    "level": 15, 
    "max": 5, 
    "next": 154, 
    "symbol": "c", 
    "symbol2": "d", 
    "url": "forensics/dna.html", 
    "url2": "forensics/skullbones.html"
  }, 
  {
    "ID": 154, 
    "index": 3, 
    "level": 15, 
    "max": 5, 
    "next": 157, 
    "symbol": "e", 
    "symbol2": "f", 
    "url": "mansion/interviews.html", 
    "url2": "mansion/guilty.html"
  }, 
  {
    "ID": 157, 
    "index": 4, 
    "level": 15, 
    "max": 5, 
    "next": 158, 
    "symbol": "g", 
    "symbol2": "h", 
    "url": "gender/determine.html", 
    "url2": "gender/enamel.html"
  }, 
  {
    "ID": 158, 
    "index": 5, 
    "level": 15, 
    "max": 5, 
    "next": 9999, 
    "symbol": "i", 
    "symbol2": "j", 
    "url": "docks/containers.html", 
    "url2": "docks/quantum.html"
  }, 
  {
    "ID": 160, 
    "index": 1, 
    "level": 16, 
    "max": 5, 
    "next": 163, 
    "symbol": "a", 
    "symbol2": "b", 
    "url": "reaction/enzyme.html", 
    "url2": "reaction/pyr_dh.html"
  }, 
  {
    "ID": 163, 
    "index": 2, 
    "level": 16, 
    "max": 5, 
    "next": 165, 
    "symbol": "c", 
    "symbol2": "d", 
    "url": "metabolism/enzymes.html", 
    "url2": "metabolism/hydratase.html"
  }, 
  {
    "ID": 165, 
    "index": 3, 
    "level": 16, 
    "max": 5, 
    "next": 166, 
    "symbol": "e", 
    "symbol2": "f", 
    "url": "pig/entry_name.html", 
    "url2": "pig/wild.html"
  }, 
  {
    "ID": 166, 
    "index": 4, 
    "level": 16, 
    "max": 5, 
    "next": 169, 
    "symbol": "g", 
    "symbol2": "h", 
    "url": "cofactor/pig.html", 
    "url2": "cofactor/superpower.html"
  }, 
  {
    "ID": 169, 
    "index": 5, 
    "level": 16, 
    "max": 5, 
    "next": 9999, 
    "symbol": "i", 
    "symbol2": "j", 
    "url": "pig_in_3d/enzyme.html", 
    "url2": "pig_in_3d/pyr_dh.html"
  }, 
  {
    "ID": 170, 
    "index": 1, 
    "level": 17, 
    "max": 2, 
    "next": 171, 
    "symbol": "a", 
    "symbol2": "b", 
    "url": "cluster/arroz.html", 
    "url2": "cluster/meal.html"
  }, 
  {
    "ID": 171, 
    "index": 2, 
    "level": 17, 
    "max": 2, 
    "next": 9999, 
    "symbol": "c", 
    "symbol2": "d", 
    "url": "multi/align.html", 
    "url2": "multi/pass.html"
  }, 
  {
    "ID": 180, 
    "index": 1, 
    "level": 18, 
    "max": 4, 
    "next": 181, 
    "symbol": "a", 
    "symbol2": "b", 
    "url": "assembly/explore2.html", 
    "url2": "assembly/sorted.html"
  }, 
  {
    "ID": 181, 
    "index": 2, 
    "level": 18, 
    "max": 4, 
    "next": 183, 
    "symbol": "c", 
    "symbol2": "d", 
    "url": "overlap/template.html", 
    "url2": "overlap/pancake.html"
  }, 
  {
    "ID": 183, 
    "index": 3, 
    "level": 18, 
    "max": 4, 
    "next": 187, 
    "symbol": "e", 
    "symbol2": "f", 
    "url": "exact/merge.html", 
    "url2": "exact/2004.html"
  }, 
  {
    "ID": 187, 
    "index": 4, 
    "level": 18, 
    "max": 4, 
    "next": 9999, 
    "symbol": "g", 
    "symbol2": "h", 
    "url": "final/fast.html", 
    "url2": "final/lies.html"
  }, 
  {
    "ID": 190, 
    "index": 1, 
    "level": 19, 
    "max": 5, 
    "next": 191, 
    "symbol": "a", 
    "symbol2": "b", 
    "url": "eyes/only.html", 
    "url2": "eyes/james_bond.html"
  }, 
  {
    "ID": 191, 
    "index": 2, 
    "level": 19, 
    "max": 5, 
    "next": 192, 
    "symbol": "c", 
    "symbol2": "d", 
    "url": "opsin/genes.html", 
    "url2": "opsin/trekking.html"
  }, 
  {
    "ID": 192, 
    "index": 3, 
    "level": 19, 
    "max": 5, 
    "next": 195, 
    "symbol": "e", 
    "symbol2": "f", 
    "url": "mining/mw_lw.html", 
    "url2": "mining/philosophy.html"
  }, 
  {
    "ID": 195, 
    "index": 4, 
    "level": 19, 
    "max": 5, 
    "next": 197, 
    "symbol": "g", 
    "symbol2": "h", 
    "url": "life/tree.html", 
    "url2": "life/deadoralive.html"
  }, 
  {
    "ID": 197, 
    "index": 5, 
    "level": 19, 
    "max": 5, 
    "next": 9999, 
    "symbol": "i", 
    "symbol2": "j", 
    "url": "howler/monkey.html", 
    "url2": "howler/fireworks.html"
  }, 
  {
    "ID": 0, 
    "index": 0, 
    "level": 0, 
    "max": 0, 
    "next": 0, 
    "symbol": "", 
    "symbol2": "", 
    "url": "", 
    "url2": ""
  }
]
