var titles = [
	"Get started ... T u t o r i a l [  updated Nov 2013]",
	"Entry format -  ... [ N E W   Dec 2013]",
	"Databases -  ... [ N E W   Nov 2014]",
	"Data mining -  ... [ N E W   Dec 2013]",
	"Bread AND Cheese OR Dessert BUT NOT Ice cream  ... [ N E W   Dec 2013]",
	"Data mining: Experts only [ N E W   Dec 2013]",
	"3D Structure [ N E W   Nov 2014]",
	"Bioinformatics Tools [ N E W   Dec 2013]",
	"Using Tools [ N E W   Jan 2013]",
	"Dot plots [ N E W   Jan 2014]",
	"Alignements [ N E W   Feb 2014]",
	"Blaaaast [ UPDATED   Mar 2014]",
	"Proteomics [ UPDATED   Sep 2014]",
	"Phylogeny ... [ N E W   Oct 2014]",
	"Could you help me? ... [ UPDATED Mar 2014]",
	"Happy sunday for 'Dee And Hey' ... [ N E W   Feb 2014]",
	"Project <i>'Notes'</i> ... [ N E W   Sep 2014]",
	"Multiple Alignment ... [ N E W   Feb 2014]",
	"Project ... [ N E W   Feb 2014]",
	"Project <i>'In your eyes only'</i> ... [ N E W   Oct 2014]",
  ];
